<a href="https://colab.research.google.com/github/donw385/Big-Data-Bowl/blob/master/Merging_large_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Make sure the datasets have a shared column of values that has the same title and is indexed the same way

In [0]:
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
#title of film
title = pd.read_table("https://datasets.imdbws.com/title.akas.tsv.gz")
title.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
1,tt0000001,2,Καρμενσίτα,GR,\N,\N,\N,0
2,tt0000001,3,Карменсита,RU,\N,\N,\N,0
3,tt0000001,4,Carmencita,US,\N,\N,\N,0
4,tt0000001,5,Carmencita,\N,\N,original,\N,1

In [0]:
#critical rating of film
review = pd.read_table("https://datasets.imdbws.com/title.ratings.tsv.gz")
review.head()

      tconst  averageRating  numVotes
0  tt0000001            5.8      1457
1  tt0000002            6.3       176
2  tt0000003            6.5      1066
3  tt0000004            6.4       105
4  tt0000005            6.2      1768

In [0]:
#directors and writers of film by internal id
directorid =  pd.read_table("https://datasets.imdbws.com/title.crew.tsv.gz")
directorid.head()

      tconst  directors writers
0  tt0000001  nm0005690      \N
1  tt0000002  nm0721526      \N
2  tt0000003  nm0721526      \N
3  tt0000004  nm0721526      \N
4  tt0000005  nm0005690      \N

review and directorid can clearly be combined on tconst without any more changes

In [0]:
tconst = directorid.merge(review, on='tconst', how='inner')
tconst.head()

      tconst  directors writers  averageRating  numVotes
0  tt0000001  nm0005690      \N            5.8      1457
1  tt0000002  nm0721526      \N            6.3       176
2  tt0000003  nm0721526      \N            6.5      1066
3  tt0000004  nm0721526      \N            6.4       105
4  tt0000005  nm0005690      \N            6.2      1768

title seems like it would combine, having the same values, but has both a different name and duplicate values that throw off the index.

In [0]:
title = title.drop(columns= ['types', 'attributes', 'language', 'region', 'ordering'])
title = title[title['isOriginalTitle'] == 1] #reduce to one instance
title.head()

      titleId                   title isOriginalTitle
4   tt0000001              Carmencita               1
5   tt0000002  Le clown et ses chiens               1
14  tt0000003          Pauvre Pierrot               1
17  tt0000004             Un bon bock               1
30  tt0000005        Blacksmith Scene               1

In [0]:
title = title.rename(columns = {'titleId':'tconst'})
title = title.reset_index(drop=True)
#drop?: by default reset_index creates an unwanted col of the previous index order
title.head()

      tconst                   title isOriginalTitle
0  tt0000001              Carmencita               1
1  tt0000002  Le clown et ses chiens               1
2  tt0000003          Pauvre Pierrot               1
3  tt0000004             Un bon bock               1
4  tt0000005        Blacksmith Scene               1

Now title can be merged

In [0]:
merged = tconst.merge(title, on='tconst', how='inner')
merged.head()

,tconst,directors,writers,averageRating,numVotes,title,isOriginalTitle
0,tt0000001,nm0005690,\N,5.8,1457,Carmencita,1
1,tt0000002,nm0721526,\N,6.3,176,Le clown et ses chiens,1
2,tt0000003,nm0721526,\N,6.5,1066,Pauvre Pierrot,1
3,tt0000004,nm0721526,\N,6.4,105,Un bon bock,1
4,tt0000005,nm0005690,\N,6.2,1768,Blacksmith Scene,1

I'm currently running into trouble because there aren't so many different csvs in this set that I can find a link column for all of them, but the way you described the football data it should be easy to connect any set to the main with an intermediate merge or two. I'm looking into how to append columns from another set when it isn't possible.

Hope this helps! -Trista